### ISSUE TITLE
Faltando função TratarResponseBody

### ISSUE THREAD

**Issue by nelsonflaviosantos** [IagooCesaar/Horse-JsonInterceptor#1]
No example1, esta chamando a função TratarResponseBody, que deveria estar no Horse.JsonInterceptor.Core.
Por isso, não compila o example1.

**Comment by IagooCesaar** [comment]
Realmente, o [exemplo 1](https://github.com/IagooCesaar/Horse-JsonInterceptor/tree/main/example/example%201) está desatualizado. Porém o [exemplo 2](https://github.com/IagooCesaar/Horse-JsonInterceptor/tree/main/example/example%202), que atua diretamente com Horse, está funcionando normalmente.

Vou subir ajustes no exemplo 1 em breve

**Comment by IagooCesaar** [comment]
Exemplo 1 atualizado.
